FROM node:latest

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json /app/
COPY frontend/tsconfig.json frontend/webpack.config.js /app/
COPY frontend/public /app/public
COPY frontend/src /app/src

RUN npm install

EXPOSE 5500

CMD ["npm", "run", "server"]
